var items = [
  { "icon": "items/1200.jpg", "name": "2077", "description": "This is the future", tags: ['red', 'violet', 'green'] },
  { "icon": "items/1200.jpg", "name": "Accidental Wealth", "description": "Get 250 coins. This is what you need.", tags: ['red', 'green'] },
  { "icon": "items/1200.jpg", "name": "Acorn", "description": "Your eggs can block bullets from enemies.", tags: ['violet'] },
  { "icon": "items/1200.jpg", "name": "Advanced Knife", "description": "The more shields you have", tags: ['red'] },
  { "icon": "items/1200.jpg", "name": "Agent Watch", "description": "Each time you pick up a key", tags: ['green'] },
  { "icon": "items/1200.jpg", "name": "Air Force Medal", "description": "Increase your weapon damage when you are in the air." },
  { "icon": "items/1200.jpg", "name": "Alien Bomb", "description": "Launches 10 heat-seeking bullets after the bomb explodes." },
  { "icon": "items/1200.jpg", "name": "Alien Tech", "description": "There's a chance you'll fire a heat-seeking bullet." },
  { "icon": "items/1200.jpg", "name": "Amethyst Necklace", "description": "Every time you pick up a coin" },
  { "icon": "items/1200.jpg", "name": "Ancient Mask", "description": "You have a chance to recover hearts each time you kill an enemy with bombs." },
  { "icon": "items/1200.jpg", "name": "Annoying Hat", "description": "You have a chance to drop extra crystals when you get hurt." },
  { "icon": "items/1200.jpg", "name": "Atlantis Bubble", "description": "Some of your bullets have shields that can block enemy bullets." },
  { "icon": "items/1200.jpg", "name": "Bad Apple", "description": "Your poison runs through their veins. All your bullets now deal poison damage." },
  { "icon": "items/1200.jpg", "name": "Bamboo Dragonfly", "description": "If you're down to half a heart" },
  { "icon": "items/1200.jpg", "name": "Battle Pass", "description": "Pay to Win! The more coins you have" },
  { "icon": "items/1200.jpg", "name": "Bear Pendant", "description": "Every time you use a key" },
  { "icon": "items/1200.jpg", "name": "Beast Amulet", "description": "It's raw power and passion" },
  { "icon": "items/1200.jpg", "name": "Beehive", "description": "There's a chance you'll fire multiple bullets." },
  { "icon": "items/1200.jpg", "name": "Beggar's Card", "description": "While in this room" },
  { "icon": "items/1200.jpg", "name": "Bent Spoon", "description": "98%....99%.... Add a crystal container and increase your gun's damage." },
  { "icon": "items/1200.jpg", "name": "Berserker Blood", "description": "The fury drive your body. The fewer hearts you have" },
  { "icon": "items/1200.jpg", "name": "Big Daddy", "description": "You're immune to explosion damage." },
  { "icon": "items/1200.jpg", "name": "Birthday Cake", "description": "A cake with " },
  { "icon": "items/1200.jpg", "name": "Black Box", "description": "Every time you use a key" },
  { "icon": "items/1200.jpg", "name": "Black Friday", "description": "It's shopping time! Everything in the shop is half price!" },
  { "icon": "items/1200.jpg", "name": "Black Rum", "description": "When you use a bomb" },
  { "icon": "items/1200.jpg", "name": "Blasting Cap 101", "description": "Your bomb will create a cross-shaped blast." },
  { "icon": "items/1200.jpg", "name": "Blasting Cap 5000", "description": "Your bomb will create an X-shaped blast." },
  { "icon": "items/1200.jpg", "name": "Blue Protocol", "description": "Let it guide you... Add shields. Upgrade your weapon." },
  { "icon": "items/1200.jpg", "name": "Blueberry Cake", "description": "You will drop extra shields if you hatch an empty egg." },
  { "icon": "items/1200.jpg", "name": "Bodyguard Glasses", "description": "Easier to aim without glare in your eyes... Increase your weapon's damage." },
  { "icon": "items/1200.jpg", "name": "Boom Gloves", "description": "Kill enough enemies" },
  { "icon": "items/1200.jpg", "name": "Brave Cookies", "description": "B.A.D. (Brave And Delicious). Add shields and a heart container." },
  { "icon": "items/1200.jpg", "name": "Broccoli", "description": "Healthy food! Contains a wide variety of vitamins! Add a heart container." },
  { "icon": "items/1200.jpg", "name": "Bullet Crown", "description": "Each time an enemy is killed in this room" },
  { "icon": "items/1200.jpg", "name": "B-Virus", "description": "Each time you kill an enemy" },
  { "icon": "items/1200.jpg", "name": "Candy Cane", "description": "The more pets you have" },
  { "icon": "items/1200.jpg", "name": "Candy Corn", "description": "The more pets you have" },
  { "icon": "items/1200.jpg", "name": "Canned Cat Food", "description": "You get some gifts from cats. Also add a heart container." },
  { "icon": "items/1200.jpg", "name": "Carp Streamer", "description": "It catches the wind - just like you! You can make an extra jump." },
  { "icon": "items/1200.jpg", "name": "Cat Medallion", "description": "This cat-faced amulet vibrates softly around magic. The fewer crystals you have" },
  { "icon": "items/1200.jpg", "name": "Chemical Burn", "description": "The explosion leaves a burst of fire behind." },
  { "icon": "items/1200.jpg", "name": "Cherry Taste", "description": "There's a chance your bullet will split into extra bullets. We know it's tempting" },
  { "icon": "items/1200.jpg", "name": "Chicken Burger", "description": "You will drop extra hearts if you hatch an empty egg." },
  { "icon": "items/1200.jpg", "name": "Chocolate Coin", "description": "Every time your pet evolves" },
  { "icon": "items/1200.jpg", "name": "Chocolate Cookies", "description": "Every time your pet evolves" },
  { "icon": "items/1200.jpg", "name": "Clay Doll", "description": "Art is an explosion! There's a chance that killing an enemy will release an explosion from you." },
  { "icon": "items/1200.jpg", "name": "Clown Hat", "description": "There's a chance you'll fire a fake rat. And who wouldn't be scared of that?" },
  { "icon": "items/1200.jpg", "name": "Coin Bomb", "description": "The coin will explode after 3 seconds if you haven't picked it up. Time is money" },
  { "icon": "items/1200.jpg", "name": "Combat Helmet", "description": "The more shields you have" },
  { "icon": "items/1200.jpg", "name": "Cooling System", "description": "Cool down your gun! All your bullets now deal ice damage." },
  { "icon": "items/1200.jpg", "name": "Creambeer", "description": "A beer that is certainlynot a milkshake. Add a heart container and a crystal container." },
  { "icon": "items/1200.jpg", "name": "Crown of Thorns", "description": "Deal melee damage to enemies who make contact with you." },
  { "icon": "items/1200.jpg", "name": "Crystal Hard Candy", "description": "Every time your pet evolves" },
  { "icon": "items/1200.jpg", "name": "Cursed Coin", "description": "Turn all wooden chests into cursed chests." },
  { "icon": "items/1200.jpg", "name": "Cyborg", "description": "Reduce your heart containers and add shields. Also increase your weapon's damage." },
  { "icon": "items/1200.jpg", "name": "Dance Mask", "description": "Upgrade your gun if you get hurt while in this room." },
  { "icon": "items/1200.jpg", "name": "Danger Sign", "description": "Your gun is full of electricity! All your bullets now deal electric damage." },
  { "icon": "items/1200.jpg", "name": "Dangerous Mine", "description": "That sound crazy or crazy AWESOME? Every time you jump" },
  { "icon": "items/1200.jpg", "name": "Dangerous Receipt", "description": "You receive delivery of a batch of bombs." },
  { "icon": "items/1200.jpg", "name": "Dark Side", "description": "If you are down to half a heart" },
  { "icon": "items/1200.jpg", "name": "Death Believer", "description": "Kill enough enemies" },
  { "icon": "items/1200.jpg", "name": "Demon Book", "description": "You have a chance to get 1 angry sprite each time you kill an enemy by bombs." },
  { "icon": "items/1200.jpg", "name": "Demon Wings", "description": "A little sacrifice goes a long way... Trade one heart container for the ability to fly." },
  { "icon": "items/1200.jpg", "name": "Devil Horn", "description": "These let you increase your weapon damage and melee damage" },
  { "icon": "items/1200.jpg", "name": "Devil Hotline", "description": "Double your melee attack damage when you are in the air." },
  { "icon": "items/1200.jpg", "name": "Devil's Trade", "description": "Each time you get hurt" },
  { "icon": "items/1200.jpg", "name": "Dimensional Bags", "description": "You have a chance to receive random goodies when you get hurt." },
  { "icon": "items/1200.jpg", "name": "Divinity", "description": "Your soul swells and you feel your feet lift off the ground... Gain the ability of flight and increase your movement speed." },
  { "icon": "items/1200.jpg", "name": "Double Yolks", "description": "Two at a time baby" },
  { "icon": "items/1200.jpg", "name": "Doughnut", "description": "The more eggs you have" },
  { "icon": "items/1200.jpg", "name": "Drilling Warhead", "description": "This is going to hurt... Increase your rate of fire and weapon damage." },
  { "icon": "items/1200.jpg", "name": "Earth Bread", "description": "An edible root known only to the Dwarves. Add a heart container." },
  { "icon": "items/1200.jpg", "name": "E-Sports Headset", "description": "Git gud. Increase your rate of fire and movement speed." },
  { "icon": "items/1200.jpg", "name": "Elastic Gel", "description": "The victory of science! Your bullet will randomly rebound when it hits the wall." },
  { "icon": "items/1200.jpg", "name": "Electric Drill", "description": "Each time you kill an enemy with melee damage" },
  { "icon": "items/1200.jpg", "name": "Electric Sheep", "description": "Do androids dream? When you have shields" },
  { "icon": "items/1200.jpg", "name": "Elf Bread", "description": "A bite can keep you going all day. Increase your movement speed and recover a heart." },
  { "icon": "items/1200.jpg", "name": "Emerald Bracelet", "description": "Every time you pick up a coin" },
  { "icon": "items/1200.jpg", "name": "Empty Can", "description": "If you don't have a key" },
  { "icon": "items/1200.jpg", "name": "Energy Cube", "description": "Each time you activate the Portal Stone" },
  { "icon": "items/1200.jpg", "name": "Eric's Candle", "description": "Your melee attack deals fire damage." },
  { "icon": "items/1200.jpg", "name": "Espresso", "description": "Feel that caffeine hit? It's BULLET TIME. Increase your rate of fire." },
  { "icon": "items/1200.jpg", "name": "Eternal Stone", "description": "You can manually cancel the hatching process of the egg by pressing [Cancel Key]." },
  { "icon": "items/1200.jpg", "name": "Evil Bracelet", "description": "Every time you use a key" },
  { "icon": "items/1200.jpg", "name": "Fanatic Mask", "description": "You have a chance to recover hearts when you get hurt by an explosion." },
  { "icon": "items/1200.jpg", "name": "Fatal Dance", "description": "You will shoot straight down while you're in the air." },
  { "icon": "items/1200.jpg", "name": "Film Magazine", "description": "Now you know Gun Fu. Add extra bullets per shot and increase your weapon's range." },
  { "icon": "items/1200.jpg", "name": "Firecrackers", "description": "There's a chance this bomb will drop a pickup after it explodes." },
  { "icon": "items/1200.jpg", "name": "Fission Device", "description": "There's a chance your bullet will split into extra bullets. Stay out of the danger zone." },
  { "icon": "items/1200.jpg", "name": "Flowerpot", "description": "There's a chance your bullet will split into extra bullets. A beautiful display of death." },
  { "icon": "items/1200.jpg", "name": "Forbidden Mask", "description": "You got a promotion! Enhance your stats in all areas." },
  { "icon": "items/1200.jpg", "name": "Fruit Popsicle", "description": "It's always summer when you're eating a popsicle. Add a heart container." },
  { "icon": "items/1200.jpg", "name": "Frying Pan", "description": "There's a chance that you'll block bullets fired at you." },
  { "icon": "items/1200.jpg", "name": "Furious Chicken", "description": "The more eggs you have" },
  { "icon": "items/1200.jpg", "name": "Future Tech", "description": "Stylish eye protection" },
  { "icon": "items/1200.jpg", "name": "Gamma Ray", "description": "Ain't nothing gonna stop you now! Your bullets can pass through walls." },
  { "icon": "items/1200.jpg", "name": "Garand Clip", "description": "Mow 'em down. Add extra bullets per shot and increase your weapon damage." },
  { "icon": "items/1200.jpg", "name": "Gas Mask", "description": "There's a chance you'll fire a poison bullet." },
  { "icon": "items/1200.jpg", "name": "Ghost Bottle", "description": "Launches 10 piercing bullets after the bomb explodes." },
  { "icon": "items/1200.jpg", "name": "Ghost Nail", "description": "There's a chance you'll fire a piercing bullet." },
  { "icon": "items/1200.jpg", "name": "Ghost Shell", "description": "You have a chance to gain shields when you get hurt. There are some questions you can't avoid." },
  { "icon": "items/1200.jpg", "name": "Giant Barbecue", "description": "Trade your IQ for POWER! Add a heart container. Increase your weapon damage" },
  { "icon": "items/1200.jpg", "name": "Gingerbread Man", "description": "If an attack kills you" },
  { "icon": "items/1200.jpg", "name": "Gladiator Helmet", "description": "Increase your melee damage every time you get hurt in the current room." },
  { "icon": "items/1200.jpg", "name": "Go Board", "description": "Winning is positioning" },
  { "icon": "items/1200.jpg", "name": "Golden Apple", "description": "The relic of the first civilization. Upgrade your weapon. Increase your movement speed slightly." },
  { "icon": "items/1200.jpg", "name": "Golden Bell", "description": "Each time you kill an enemy with melee damage" },
  { "icon": "items/1200.jpg", "name": "Golden Bird", "description": "The more coins you have" },
  { "icon": "items/1200.jpg", "name": "Golden Fist", "description": "Each time you destroy a wooden box using melee damage" },
  { "icon": "items/1200.jpg", "name": "Golden Skulls", "description": "The more coins you have" },
  { "icon": "items/1200.jpg", "name": "Golden Statuette", "description": "You have a chance to get a guard sprite when you use coins. Don't you want to kiss it?" },
  { "icon": "items/1200.jpg", "name": "Golden Teeth", "description": "Oof. Hope you like soup. Drop coins when you get hurt." },
  { "icon": "items/1200.jpg", "name": "Golden Torch", "description": "The light is warm. Get an extra treasure room at each new level." },
  { "icon": "items/1200.jpg", "name": "Grape Candy", "description": "You will drop an extra crystal if you hatch an empty egg." },
  { "icon": "items/1200.jpg", "name": "Green Cap", "description": "This green cap will diminish you... That is" },
  { "icon": "items/1200.jpg", "name": "Grim Hood", "description": "Each time an enemy is killed in this room" },
  { "icon": "items/1200.jpg", "name": "Gum Bear", "description": "Yeah! Increase the damage from all your pets." },
  { "icon": "items/1200.jpg", "name": "Gunpowder Plot", "description": "Each time you pick up a bomb" },
  { "icon": "items/1200.jpg", "name": "Hacking Tool", "description": "I got this! Keys are no longer a problem." },
  { "icon": "items/1200.jpg", "name": "Hair Dryer", "description": "Let it blow your bullets farther" },
  { "icon": "items/1200.jpg", "name": "Hand Mirror", "description": "There's a chance you'll fire a ricocheting bullet." },
  { "icon": "items/1200.jpg", "name": "Hard Hat", "description": "You won't take any environmental damage." },
  { "icon": "items/1200.jpg", "name": "Hard Mints", "description": "Every time your pet evolves" },
  { "icon": "items/1200.jpg", "name": "Headband", "description": "The more times you jump" },
  { "icon": "items/1200.jpg", "name": "Heart Key", "description": "If you don't have a key" },
  { "icon": "items/1200.jpg", "name": "Heart Necklace", "description": "Every time you use a key" },
  { "icon": "items/1200.jpg", "name": "Heart of Fire", "description": "You can revive after death" },
  { "icon": "items/1200.jpg", "name": "Heart of the Ocean", "description": "The power of love! Add shields. Increase your weapon's damage." },
  { "icon": "items/1200.jpg", "name": "Hiccups", "description": "You will get a random item if you get hurt 6 times in the same room." },
  { "icon": "items/1200.jpg", "name": "Hip Flask", "description": "Take a shot. Take the shot. Rinse and repeat. Greatly increase your weapon damage." },
  { "icon": "items/1200.jpg", "name": "Hero Mask", "description": "This is your calling. Increase your jump height and movement speed." },
  { "icon": "items/1200.jpg", "name": "Hot Chili", "description": "Let your gun burn! All your bullets now deal fire damage." },
  { "icon": "items/1200.jpg", "name": "Howard Reactor", "description": "Hearts will be replaced by shields when they drop. The creator slightly modified the rules of the universe." },
  { "icon": "items/1200.jpg", "name": "Hungry Amulet", "description": "Kill enough enemies in melee" },
  { "icon": "items/1200.jpg", "name": "Hunter Queen", "description": "Your melee attacks cause enemies to explode when they die." },
  { "icon": "items/1200.jpg", "name": "Immortal Heart", "description": "This is a legendary trophy. You can revive after death. (Can only be used once.)" },
  { "icon": "items/1200.jpg", "name": "Imperial Force", "description": "There's a chance you'll fire a laser. Whether or not it hits anything is another matter..." },
  { "icon": "items/1200.jpg", "name": "Inner Eye", "description": "You can preview the description of an item without picking it up." },
  { "icon": "items/1200.jpg", "name": "Inorganic Mod", "description": "You have a chance to drop extra shields each time you kill an enemy." },
  { "icon": "items/1200.jpg", "name": "Iron Crown", "description": "There's a chance your bullet will create a beautiful firework." },
  { "icon": "items/1200.jpg", "name": "Iron Frog", "description": "Launches 10 bouncy bullets after the bomb explodes." },
  { "icon": "items/1200.jpg", "name": "Iron Heart", "description": "You will lose hearts first even if you have shields. You are gradually accepting this fact." },
  { "icon": "items/1200.jpg", "name": "Jelly Beans", "description": "You have a chance to shoot random element bullets." },
  { "icon": "items/1200.jpg", "name": "Jewelry Box", "description": "Every time you use a key" },
  { "icon": "items/1200.jpg", "name": "Kendo Mask", "description": "There's a chance that you'll block melee damage from enemies." },
  { "icon": "items/1200.jpg", "name": "Kinetic Blade", "description": "Gain shields after killing enemies with melee damage." },
  { "icon": "items/1200.jpg", "name": "King's Crown", "description": "Your weapon does more damage when you're at full hearts." },
  { "icon": "items/1200.jpg", "name": "Knife and Fork", "description": "Each time you kill an enemy with melee damage" },
  { "icon": "items/1200.jpg", "name": "Kongming Lantern", "description": "You have a chance to get a guard sprite when you get hurt." },
  { "icon": "items/1200.jpg", "name": "Last Hope", "description": "You fight for humanity! After each battle" },
  { "icon": "items/1200.jpg", "name": "Lemon Candy", "description": "The more eggs you have" },
  { "icon": "items/1200.jpg", "name": "Lidless Eye", "description": "It sees ...... EVERYTHING! Including your inner desires and fears. Maps are revealed in every level." },
  { "icon": "items/1200.jpg", "name": "Like of the King", "description": "You have the King's approval. Upgrade your weapon. Increase your bullet velocity." },
  { "icon": "items/1200.jpg", "name": "Lion Headgear", "description": "The more pets you have" },
  { "icon": "items/1200.jpg", "name": "Lipstick", "description": "Don't get it on your teeth. The shop will now replenish." },
  { "icon": "items/1200.jpg", "name": "Lithium Battery", "description": "There's a chance you'll fire an electric bullet." },
  { "icon": "items/1200.jpg", "name": "Little Pickaxe", "description": "A very useful tool. Reveal all nearby hidden rooms." },
  { "icon": "items/1200.jpg", "name": "Locksmith", "description": "If you don't have a key" },
  { "icon": "items/1200.jpg", "name": "Lottery Tickets", "description": "777 coins! You feel extremely lucky... and lonely." },
  { "icon": "items/1200.jpg", "name": "Mad Mask", "description": "This IS the craziest thing you've ever seen. Greatly increase your rate of fire." },
  { "icon": "items/1200.jpg", "name": "Magic Vortex", "description": "Your weapon does more damage when your crystal containers are full. You have a big plan." },
  { "icon": "items/1200.jpg", "name": "Magic Wand", "description": "You have a chance to gain crystals when you get hurt." },
  { "icon": "items/1200.jpg", "name": "Magical Bean", "description": "This unbelievable bean will recover all your hearts and increase your weapon's range." },
  { "icon": "items/1200.jpg", "name": "Magician Hat", "description": "Each time you pick up a key" },
  { "icon": "items/1200.jpg", "name": "Maneki-Neko", "description": "Meow... You get an extra bonus when you pick up coins." },
  { "icon": "items/1200.jpg", "name": "Marshmallow", "description": "When you're at full health" },
  { "icon": "items/1200.jpg", "name": "Matchbox", "description": "If the egg touches stone - such as doors or chests - they'll both explode and disappear." },
  { "icon": "items/1200.jpg", "name": "Medal of Honor", "description": "It's about discipline. Increase your movement speed and your weapon damage." },
  { "icon": "items/1200.jpg", "name": "Melting Calendar", "description": "Movement speed increases." },
  { "icon": "items/1200.jpg", "name": "Metal Crown", "description": "There's a chance your bullet will create a beautiful firework." },
  { "icon": "items/1200.jpg", "name": "Metal Panties", "description": "Make them regret ever touching you. Drop 6 instant bombs when you get hurt." },
  { "icon": "items/1200.jpg", "name": "Mercenary Lord", "description": "The more coins you have" },
  { "icon": "items/1200.jpg", "name": "Mercy Hood", "description": "May the love be with you. Double the amount of hearts recovered." },
  { "icon": "items/1200.jpg", "name": "Midnight Mask", "description": "It's Friday! Increase your weapon's damage when you get hurt." },
  { "icon": "items/1200.jpg", "name": "Mini Radar", "description": "BEEP. BEEP. BEEP. Mark all secrets on your map." },
  { "icon": "items/1200.jpg", "name": "Mjolnir", "description": "Your melee attack deals electric damage." },
  { "icon": "items/1200.jpg", "name": "Monk Hat", "description": "Add a heart container and a crystal container. Keep the sun and rain off your face so you can concentrate on meditating." },
  { "icon": "items/1200.jpg", "name": "Monocle", "description": "You will drop an extra key if you hatch an empty egg." },
  { "icon": "items/1200.jpg", "name": "Most Wanted List", "description": "You get twice the coins after you kill enemies." },
  { "icon": "items/1200.jpg", "name": "Motorcycle Helmet", "description": "Increase your movement speed" },
  { "icon": "items/1200.jpg", "name": "Mustard Poop", "description": "Eggs can cause touch damage to enemies." },
  { "icon": "items/1200.jpg", "name": "Mutated Orange", "description": "This orange will make you SUPER strong. Increase your movement speed and weapon damage." },
  { "icon": "items/1200.jpg", "name": "Nanotechnology", "description": "After the bomb explodes" },
  { "icon": "items/1200.jpg", "name": "Nerve System 6.0", "description": "Increase your weapon damage and movement speed. Forget the sheep" },
  { "icon": "items/1200.jpg", "name": "Nightmare Mask", "description": "You have a chance to get a evil sprite when you get hurt." },
  { "icon": "items/1200.jpg", "name": "Night Vision", "description": "Fire a special bullet every ten shots" },
  { "icon": "items/1200.jpg", "name": "Ninja Costume", "description": "No one will ever see you coming. You can make an extra jump. Increase your melee damage." },
  { "icon": "items/1200.jpg", "name": "Nougat", "description": "Every time your pet evolves" },
  { "icon": "items/1200.jpg", "name": "Onion Helmet", "description": "You get a temporary protective shell per room." },
  { "icon": "items/1200.jpg", "name": "Ordinary Gloves", "description": "100 push-ups" },
  { "icon": "items/1200.jpg", "name": "Pain Drop", "description": "Fight through the pain. Let it give you strength. Increase you weapon damage and rate of fire." },
  { "icon": "items/1200.jpg", "name": "Paper Plane", "description": "Let it catch the breeze... Increase your weapon’s range and damage." },
  { "icon": "items/1200.jpg", "name": "Paper Windmills", "description": "Exhale as you pull the trigger to give your bullets a bit more oomph. Increase your rate of fire and weapon damage." },
  { "icon": "items/1200.jpg", "name": "Party Popper", "description": "Launches 10 bullets after the bomb explodes." },
  { "icon": "items/1200.jpg", "name": "Pegasus", "description": "You feel strong" },
  { "icon": "items/1200.jpg", "name": "Pen No. 7", "description": "You can use keys as bombs when you don't have any bombs." },
  { "icon": "items/1200.jpg", "name": "Pepper Soup", "description": "It'll bring tears to your eyes! ...Why" },
  { "icon": "items/1200.jpg", "name": "Persian Turban", "description": "The beautiful gem in this turban functions as a number of crystal containers." },
  { "icon": "items/1200.jpg", "name": "Ping Pong", "description": "There's a chance you'll fire a bouncy bullet." },
  { "icon": "items/1200.jpg", "name": "Pink Dart", "description": "Let the feathered tip wing you on your way to victory. Increase your weapon's range and rate of fire." },
  { "icon": "items/1200.jpg", "name": "Plan B", "description": "Keys are not the only answer! You have a chance to unlock chests or doors with explosions." },
  { "icon": "items/1200.jpg", "name": "Plague Mask", "description": "You have a chance of recovering half a heart each time you kill an enemy." },
  { "icon": "items/1200.jpg", "name": "Player Zero Ready", "description": "Don't let up! The more enemies you hit without stopping" },
  { "icon": "items/1200.jpg", "name": "Police Badge", "description": "Add extra bullets per shot and increase your bullet velocity." },
  { "icon": "items/1200.jpg", "name": "Popcorn", "description": "All your bullets will explode on impact or after they travel a certain distance. Enjoy the show." },
  { "icon": "items/1200.jpg", "name": "Power Diamond", "description": "ABSOLUTE POWER! Upgrade your weapon" },
  { "icon": "items/1200.jpg", "name": "Power Helmet", "description": "If you get hurt in this room" },
  { "icon": "items/1200.jpg", "name": "Prophet Chip", "description": "Kill enough enemies" },
  { "icon": "items/1200.jpg", "name": "Protein Powder", "description": "The more eggs you have" },
  { "icon": "items/1200.jpg", "name": "Pumpkin Head", "description": "When you get hurt" },
  { "icon": "items/1200.jpg", "name": "Quantum Core", "description": "Increase your gun's damage and add shields.An incredible source of power. You've no idea how it works. Strings" },
  { "icon": "items/1200.jpg", "name": "Rabbit Ears", "description": "You wouldn't wear them if they weren't useful" },
  { "icon": "items/1200.jpg", "name": "Rabbit Doll", "description": "[Characteristics] Saya has two different battle forms for ranged attacks and melee attacks. Use  to switch weapons between the gun and the katana." },
  { "icon": "items/1200.jpg", "name": "Rainbow Candy", "description": "Every time your pet evolves" },
  { "icon": "items/1200.jpg", "name": "Rainforest Souvenir", "description": "Kill enough enemies" },
  { "icon": "items/1200.jpg", "name": "Red Flag", "description": "Instead of throwing a bomb" },
  { "icon": "items/1200.jpg", "name": "Red Hat", "description": "It's time to play! It's time to have some fun. Jumping can cause damage to enemies." },
  { "icon": "items/1200.jpg", "name": "Ready Aim Eye", "description": "Each time an enemy is killed in this room" },
  { "icon": "items/1200.jpg", "name": "Ritual Mask", "description": "Add a crystal container. You can recover hearts by using 5 crystals" },
  { "icon": "items/1200.jpg", "name": "Robot Armor", "description": "You have a chance to drop extra shields when you get hurt." },
  { "icon": "items/1200.jpg", "name": "Rocket Mod", "description": "There's a chance you'll fire a heat-seeking rocket." },
  { "icon": "items/1200.jpg", "name": "Rogue's Badge", "description": "While in this room" },
  { "icon": "items/1200.jpg", "name": "Roly-Poly Toy", "description": "You will drop an extra bomb if you hatch an empty egg." },
  { "icon": "items/1200.jpg", "name": "Royal Antlers", "description": "Increase your movement speed. You'll drop extra coins when you use keys." },
  { "icon": "items/1200.jpg", "name": "Ruby Earrings", "description": "Every time you pick up a coin" },
  { "icon": "items/1200.jpg", "name": "Running Shoes", "description": "The sweet sneakers will increase your movement speed. Gotta go fast." },
  { "icon": "items/1200.jpg", "name": "Rusty Key", "description": "Every time you use a key" },
  { "icon": "items/1200.jpg", "name": "Sacred Tears", "description": "You have a chance to get a protective shell each time you kill an enemy by bombs." },
  { "icon": "items/1200.jpg", "name": "Samurai's Soul", "description": "There's a chance you'll fire a big bullet." },
  { "icon": "items/1200.jpg", "name": "Sapper Backpack", "description": "Bombs explode bigger" },
  { "icon": "items/1200.jpg", "name": "Sapphire Ring", "description": "Every time you pick up a coin" },
  { "icon": "items/1200.jpg", "name": "Saturn Lollipop", "description": "The more eggs you have" },
  { "icon": "items/1200.jpg", "name": "Scarlet Tale", "description": "Increase your rate of fire if you get hurt while in this room." },
  { "icon": "items/1200.jpg", "name": "Schrödinger's Bet", "description": "Are you dead or are you alive? You won't know until you die and wake up... and there's a chance you might." },
  { "icon": "items/1200.jpg", "name": "Screwdriver", "description": "Kill enough enemies" },
  { "icon": "items/1200.jpg", "name": "Seals Patch", "description": "You've worked for this. Upgrade your weapon. Increase your movement speed." },
  { "icon": "items/1200.jpg", "name": "Seed of Stone", "description": "Your bullet will create a platform on the wall." },
  { "icon": "items/1200.jpg", "name": "Shadow Blade", "description": "Nothing is True. Everything is Permitted. Do more weapon damage when you attack from behind." },
  { "icon": "items/1200.jpg", "name": "Shadow Operation", "description": "They'll never see you coming. Increase your weapon's range and movement speed." },
  { "icon": "items/1200.jpg", "name": "Shaman Mask", "description": "After you activate all the Portal Stones" },
  { "icon": "items/1200.jpg", "name": "Shark Bait", "description": "You can use eggs as bombs when you don't have any bombs." },
  { "icon": "items/1200.jpg", "name": "Shroud", "description": "Add a crystal container. You can gain crystals after killing an enemy." },
  { "icon": "items/1200.jpg", "name": "Silver Compass", "description": "Reveal the truth. Show all rooms on your map." },
  { "icon": "items/1200.jpg", "name": "Silver Brooch", "description": "Every time you pick up a coin" },
  { "icon": "items/1200.jpg", "name": "Slayer of Demons", "description": "Kill enough enemies" },
  { "icon": "items/1200.jpg", "name": "Slingshot", "description": "Pull back... Exhale slowly... Let go! TWANG! Add extra bullets per shot and increase your weapon's range." },
  { "icon": "items/1200.jpg", "name": "Smiley Bomb", "description": "Your bomb will clear a certain area of bullets." },
  { "icon": "items/1200.jpg", "name": "Smithing Hammer", "description": "Clang. Clang. Clang. Upgrade your weapon. Increase your weapon damage." },
  { "icon": "items/1200.jpg", "name": "Snack Box", "description": "Eggs will hatch random pickups instead of pets." },
  { "icon": "items/1200.jpg", "name": "Snow Globe", "description": "There's a chance you'll fire an ice bullet." },
  { "icon": "items/1200.jpg", "name": "Soldier Mask", "description": "Peekaboo! I see you! There's a chance your bullets will track enemies." },
  { "icon": "items/1200.jpg", "name": "Soul Flask", "description": "You hear whispers within the bottle... Add a heart container and recover some hearts." },
  { "icon": "items/1200.jpg", "name": "Space Helmet", "description": "To infinity... Increase your jump height." },
  { "icon": "items/1200.jpg", "name": "Space Soda", "description": "Atomized Cola" },
  { "icon": "items/1200.jpg", "name": "Space Spanner", "description": "Each time you kill an enemy with melee damage" },
  { "icon": "items/1200.jpg", "name": "Spartan Lineage", "description": "The fewer hearts you have" },
  { "icon": "items/1200.jpg", "name": "Spear of Destiny", "description": "Sometimes" },
  { "icon": "items/1200.jpg", "name": "Stark Module", "description": "Increase your weapon damage and bullet velocity. Stark Brilliance(TM). (Stark is not responsible for any loss of limbs)" },
  { "icon": "items/1200.jpg", "name": "Steel Gear", "description": "The more keys you have" },
  { "icon": "items/1200.jpg", "name": "Strange Mask", "description": "Ssssssomebody stop me! Add extra bullets per shot and a shield." },
  { "icon": "items/1200.jpg", "name": "Strawberry Candy", "description": "The more pets you have" },
  { "icon": "items/1200.jpg", "name": "Sturdy Shield", "description": "You've never felt stronger. Or better-looking. Add shields. Some attacks will deal no damage to you." },
  { "icon": "items/1200.jpg", "name": "Sun Coin", "description": "You can revive after death" },
  { "icon": "items/1200.jpg", "name": "Super Logo", "description": "You're at the top of your game. Upgrade your weapon. Increase your jump height and movement speed slightly." },
  { "icon": "items/1200.jpg", "name": "Szechuan Sauce", "description": "There's a chance you'll fire a flame bullet." },
  { "icon": "items/1200.jpg", "name": "Tanghulu", "description": "A stick of candied hawthorn. Add a heart container." },
  { "icon": "items/1200.jpg", "name": "Telescopic Sight", "description": "Increase your weapon's range. Also increase your jump height." },
  { "icon": "items/1200.jpg", "name": "Tesla Coil", "description": "A ring of lightning will surround you and damage nearby enemies." },
  { "icon": "items/1200.jpg", "name": "The Crowbar", "description": "Your favorite weapon! Increase your melee attack damage." },
  { "icon": "items/1200.jpg", "name": "The Towel", "description": "DON'T PANIC! You'll only lose half a heart when you get hurt." },
  { "icon": "items/1200.jpg", "name": "Thunder Engine", "description": "The more shields you have" },
  { "icon": "items/1200.jpg", "name": "Tobe Beef", "description": "The best beef EVER. Add a heart container." },
  { "icon": "items/1200.jpg", "name": "Toffee Apple", "description": "Every time your pet evolves" },
  { "icon": "items/1200.jpg", "name": "Toy Home Run Bat", "description": "The more eggs you have" },
  { "icon": "items/1200.jpg", "name": "Traveler Hood", "description": "Travel farther than ever before. You can make an extra jump." },
  { "icon": "items/1200.jpg", "name": "Treasure Map", "description": "You can see a faint signature on the back - Captain Jack S....? Mark all hidden rooms on your map." },
  { "icon": "items/1200.jpg", "name": "Turtle Hat", "description": "There's a chance that you'll block damage taken from behind." },
  { "icon": "items/1200.jpg", "name": "Unknown Mask", "description": "An extravagant crystal mask. It can be used as a crystal container and adds a shield - because no one wants to hit it." },
  { "icon": "items/1200.jpg", "name": "Vanilla Ice Cream", "description": "The more eggs you have" },
  { "icon": "items/1200.jpg", "name": "Virtual Assistant", "description": "When you lose a shield" },
  { "icon": "items/1200.jpg", "name": "V.O. Field", "description": "If you're down to half a heart" },
  { "icon": "items/1200.jpg", "name": "Void Coin", "description": "There's a hole in the world... in your soul. Increase your weapon damage and rate of fire." },
  { "icon": "items/1200.jpg", "name": "Wade Tech", "description": "It looks easy enough to install... Upgrade your weapon. Increase your rate of fire." },
  { "icon": "items/1200.jpg", "name": "War Hammer", "description": "Each time you kill an enemy with melee damage" },
  { "icon": "items/1200.jpg", "name": "Welding Mask", "description": "You have a chance to drop extra keys when you get hurt by an explosion." },
  { "icon": "items/1200.jpg", "name": "Whetstone", "description": "While in this room" },
  { "icon": "items/1200.jpg", "name": "Winged Hat", "description": "The little wings are so darn cute. And they let you make an extra jump." },
  { "icon": "items/1200.jpg", "name": "Wings of Wisdom", "description": "You can fly now! Gain the ability of flight and reduces one heart container." },
  { "icon": "items/1200.jpg", "name": "Wizard Sword", "description": "Each time you kill an enemy with melee damage" },
  { "icon": "items/1200.jpg", "name": "Worst Blowing Gum", "description": "The more pets you have" },
  { "icon": "items/1200.jpg", "name": "X-Ray", "description": "Your bullets can pass through enemies." },
]